#!/bin/bash

set -o xtrace

# curl -XPUT "http://localhost:9200/tweet/_doc/1" -H 'Content-Type: application/json' -d'
# {
#   "date": "2022-02-22 10:17:00",
#   "message": "Le problème dans ce monde...1"
# }'

# curl -XPUT "http://localhost:9200/tweet/_doc/2" -H 'Content-Type: application/json' -d'
# {
#   "date": "2022-02-22 10:17:00",
#   "message": "Le problème dans ce monde...2"
# }'

# curl -XPUT "http://localhost:9200/tweet/_doc/3" -H 'Content-Type: application/json' -d'
# {
#   "date": "2022-02-22 10:17:00",
#   "message": "Le problème dans ce monde...3"
# }'


# curl -XPUT "http://localhost:9200/user/_doc/1" -H 'Content-Type: application/json' -d'
# {
#   "gender": "binary",
#   "age": 55,
#   "first_name": "John1",
#   "last_name": "Doe1",
# }'

# curl -XPUT "http://localhost:9200/user/_doc/2" -H 'Content-Type: application/json' -d'
# {
#   "gender": "binary",
#   "age": 55,
#   "first_name": "John2",
#   "last_name": "Doe2",
# }'

# curl -XPUT "http://localhost:9200/user/_doc/3" -H 'Content-Type: application/json' -d'
# {
#   "gender": "binary",
#   "age": 55,
#   "first_name": "John3",
#   "last_name": "Doe3",
# }'

curl -XPUT "http://localhost:9200/tweet/_doc/1" -H 'Content-Type: application/json' -d'
{
  "date": "2022-02-22 10:00:00",
  "message": "Le problème dans ce monde...1"
}'

curl -XPUT "http://localhost:9200/tweet/_doc/2" -H 'Content-Type: application/json' -d'
{
  "date": "2022-02-22 10:17:00",
  "message": "Le problème dans ce monde...2"
}'

curl -XPUT "http://localhost:9200/user/_doc/8" -H 'Content-Type: application/json' -d'
{ 
    "gender": "binary",
    "age": 55,
    "first_name": "John3",
    "last_name": "Doe3",
    "tweets": [ 
        {
            "id": "1"
        },
        {
            "id": "2"
        }
    ] 
}'